name: Invoke Update llmzip.github.io Events

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-git-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: llmzip.github.io

      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api octocat

      - name: Dispatch event to update llmzip.github.io
        run: gh api /repos/llmzip/llmzip.github.io/dispatches -f event_type='update-git-submodule'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
