name: Update llmzip.github.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-git-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout llmzip.github.io repository
        uses: actions/checkout@v3
        with:
          repository: llmzip/llmzip.github.io
          path: github-io

      - name: Update llmzip.github.io submodule
        run: |
          git submodule update --remote --merge
          git add .
        working-directory: github-io

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
